version: '2'
services:
  kafka:
    image: spotify/kafka
    ports:
     - "2181:2181"
     - "9092:9092"
    environment:
     - NUM_PARTITIONS=9
     - ADVERTISED_PORT=9092
     - ADVERTISED_HOST=127.0.0.1
